### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Ablex222** [Banh-Canh/Manga-Tagger#1]
**OS**: What operating system are you running Manga Tagger on?
Synology (Linux)
**Manga Tagger Version:** What version of Manga Tagger are you running?
Latest Docker
**Description of the issue:** Give a a clear and concise description of what the issue is.
Program not accurately writing data for second chapter. It looks as if its taking the volume number and thinking that is the chapter value. Could be due to expanding the accepted parameters. 
**Manga Series:** What manga series (singular or plural) were being tagged when the issue was encountered?

**Screenshots (If applicable):** Add screenshots to help explain your problem.
2021-02-28 16:49:16,889 | MainThread 140035010194248 | MangaTaggerLib.database.Database | INFO - Establishing database connection...
2021-02-28 16:49:16,894 | MainThread 140035010194248 | MangaTaggerLib.database.Database | INFO - Database connection established!
2021-02-28 16:49:16,895 | MainThread 140035010194248 | MangaTaggerLib.utils.AppSettings | INFO - Download directory has been set as "/downloads"
2021-02-28 16:49:16,896 | MainThread 140035010194248 | MangaTaggerLib.database.ProcSeriesTable | INFO - Loading processed series...
2021-02-28 16:49:16,920 | MainThread 140035010194248 | MangaTaggerLib.database.TaskQueueTable | INFO - Loading task queue...
2021-02-28 16:49:16,922 | MainThread 140035010194248 | MangaTaggerLib.database.TaskQueueTable | INFO - Attempting to delete all records in the database...
2021-02-28 16:49:16,923 | MainThread 140035010194248 | MangaTaggerLib.database.TaskQueueTable | INFO - Deletion was successful!
2021-02-28 16:49:16,924 | MainThread 140035010194248 | MangaTaggerLib.MangaTaggerLib | INFO - Starting Manga Tagger - Version 1.1.6-alpha
2021-02-28 16:49:16,943 | MainThread 140035010194248 | MangaTaggerLib.task_queue.QueueWorker | INFO - Watching "/downloads" for new downloads
2021-02-28 16:49:32,756 | Thread-1 140034501749560 | MangaTaggerLib.task_queue.SeriesHandler | INFO - Creation event for "/downloads/xxxxxxxx/xxxxxxxx -.- Vol. 01 Ch. 001.cbz" will be added to the queue
2021-02-28 16:49:32,757 | MTT-5 140034507447096 | MangaTaggerLib.task_queue.QueueWorker | INFO - Pulling "file created" event from the queue for "/downloads/xxxxxxxx/xxxxxxxx -.- Vol. 01 Ch. 001.cbz"
2021-02-28 16:49:32,876 | Thread-1 140034501749560 | MangaTaggerLib.task_queue.SeriesHandler | INFO - Creation event for "/downloads/xxxxxxxx/xxxxxxxx -.- Vol. 01 Ch. 002 - Time Paradox.cbz" will be added to the queue
2021-02-28 16:49:32,877 | MTT-4 140034508569400 | MangaTaggerLib.task_queue.QueueWorker | INFO - Pulling "file created" event from the queue for "/downloads/xxxxxxxx/xxxxxxxx -.- Vol. 01 Ch. 002 - Time Paradox.cbz"
2021-02-28 16:49:33,764 | MTT-5 140034507447096 | MangaTaggerLib.MangaTaggerLib | INFO - Now processing "/downloads/xxxxxxxx/xxxxxxxx -.- Vol. 01 Ch. 001.cbz"...
2021-02-28 16:49:33,764 | MTT-5 140034507447096 | MangaTaggerLib.MangaTaggerLib | INFO - Attempting to rename "xxxxxxxx -.- Vol. 01 Ch. 001.cbz"...
2021-02-28 16:49:33,765 | MTT-5 140034507447096 | MangaTaggerLib.MangaTaggerLib | INFO - Filename was successfully parsed as ['xxxxxxxx', 'Vol. 01 Ch. 001.cbz'].
2021-02-28 16:49:33,766 | MTT-5 140034507447096 | MangaTaggerLib.MangaTaggerLib | INFO - File will be renamed to "xxxxxxxx 001.cbz".
2021-02-28 16:49:33,767 | MTT-5 140034507447096 | MangaTaggerLib.MangaTaggerLib | INFO - A directory for "xxxxxxxx" in "/manga" does not exist; creating now.
2021-02-28 16:49:33,768 | MTT-5 140034507447096 | MangaTaggerLib.MangaTaggerLib | INFO - Checking for current and previously processed files with filename "xxxxxxxx 001.cbz"...
2021-02-28 16:49:33,770 | MTT-5 140034507447096 | MangaTaggerLib.MangaTaggerLib | INFO - No files currently currently being processed under the filename "xxxxxxxx 001.cbz". Locking new filename for processing...
2021-02-28 16:49:33,773 | MTT-5 140034507447096 | MangaTaggerLib.MangaTaggerLib | INFO - "xxxxxxxx" chapter 001 has not been processed before. Proceeding with file rename...
2021-02-28 16:49:33,881 | MTT-4 140034508569400 | MangaTaggerLib.MangaTaggerLib | INFO - Now processing "/downloads/xxxxxxxx/xxxxxxxx -.- Vol. 01 Ch. 002 - Time Paradox.cbz"...
2021-02-28 16:49:33,882 | MTT-4 140034508569400 | MangaTaggerLib.MangaTaggerLib | INFO - Attempting to rename "xxxxxxxx -.- Vol. 01 Ch. 002 - Time Paradox.cbz"...
2021-02-28 16:49:33,883 | MTT-4 140034508569400 | MangaTaggerLib.MangaTaggerLib | INFO - Filename was successfully parsed as ['xxxxxxxx', 'Vol. 01 Ch. 002 - Time Paradox.cbz'].
2021-02-28 16:49:33,885 | MTT-4 140034508569400 | MangaTaggerLib.MangaTaggerLib | INFO - File will be renamed to "xxxxxxxx 001.cbz".
2021-02-28 16:49:33,886 | MTT-4 140034508569400 | MangaTaggerLib.MangaTaggerLib | INFO - Checking for current and previously processed files with filename "xxxxxxxx 001.cbz"...
2021-02-28 16:49:33,887 | MTT-4 140034508569400 | MangaTaggerLib.MangaTaggerLib | INFO - A file is currently being renamed under the filename "xxxxxxxx 001.cbz". Locking /downloads/xxxxxxxx/xxxxxxxx -.- Vol. 01 Ch. 002 - Time Paradox.cbz from further processing until this rename action is complete...
2021-02-28 16:49:33,904 | MTT-5 140034507447096 | MangaTaggerLib.database.ProcFilesTable | INFO - "xxxxxxxx 001" has been renamed.
2021-02-28 16:49:34,164 | MTT-5 140034507447096 | MangaTaggerLib.MangaTaggerLib | INFO - "xxxxxxxx 001.cbz" will be unlocked for any pending processes.
2021-02-28 16:49:34,165 | MTT-5 140034507447096 | MangaTaggerLib.MangaTaggerLib | INFO - "xxxxxxxx" has not been processed as a searched series nor is it currently pending a database search. Locking series from being processing until database has been searched...
2021-02-28 16:49:34,166 | MTT-5 140034507447096 | MangaTaggerLib.MangaTaggerLib | INFO - Table search value is "xxxxxxxx"
2021-02-28 16:49:34,167 | MTT-5 140034507447096 | MangaTaggerLib.MangaTaggerLib | INFO - Searching manga_metadata for manga title by search value...
2021-02-28 16:49:34,169 | MTT-5 140034507447096 | MangaTaggerLib.MangaTaggerLib | INFO - Searching manga_metadata for regular manga title...
2021-02-28 16:49:34,171 | MTT-5 140034507447096 | MangaTaggerLib.MangaTaggerLib | INFO - Searching manga_metadata for English manga title...
2021-02-28 16:49:34,174 | MTT-5 140034507447096 | MangaTaggerLib.MangaTaggerLib | INFO - Manga was not found in the database; resorting to Jikan API.
2021-02-28 16:49:34,889 | MTT-4 140034508569400 | MangaTaggerLib.MangaTaggerLib | INFO - The file being renamed to "/manga/xxxxxxxx/xxxxxxxx 001.cbz" has been completed. Unlocking "xxxxxxxx 001.cbz" for file rename processing.
2021-02-28 16:49:34,892 | MTT-4 140034508569400 | MangaTaggerLib.MangaTaggerLib | WARNING - No changes have been found for "xxxxxxxx 001.cbz"; file currently being processed will be deleted
2021-02-28 16:49:34,896 | MTT-4 140034508569400 | MangaTaggerLib.MangaTaggerLib | ERROR - "xxxxxxxx -.- Vol. 01 Ch. 002 - Time Paradox.cbz" has already been processed by Manga Tagger; skipping
Traceback (most recent call last):
File "/Manga-Tagger/MangaTaggerLib/MangaTaggerLib.py", line 104, in process_manga_chapter
rename_action(file_path, new_file_path, directory_name, manga_details[1], logging_info)
File "/Manga-Tagger/MangaTaggerLib/MangaTaggerLib.py", line 284, in rename_action
raise FileAlreadyProcessedError(current_file_path.name)
MangaTaggerLib.errors.FileAlreadyProcessedError: "xxxxxxxx -.- Vol. 01 Ch. 002 - Time Paradox.cbz" has already been processed by Manga Tagger; skipping
2021-02-28 16:49:34,898 | MTT-4 140034508569400 | MangaTaggerLib.task_queue.QueueWorker | ERROR - PosixPath('/manga/xxxxxxxx/xxxxxxxx 001.cbz')
Traceback (most recent call last):
File "/Manga-Tagger/MangaTaggerLib/MangaTaggerLib.py", line 104, in process_manga_chapter
rename_action(file_path, new_file_path, directory_name, manga_details[1], logging_info)
File "/Manga-Tagger/MangaTaggerLib/MangaTaggerLib.py", line 284, in rename_action
raise FileAlreadyProcessedError(current_file_path.name)
MangaTaggerLib.errors.FileAlreadyProcessedError: "xxxxxxxx -.- Vol. 01 Ch. 002 - Time Paradox.cbz" has already been processed by Manga Tagger; skipping

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/Manga-Tagger/MangaTaggerLib/task_queue.py", line 188, in process
MangaTaggerLib.process_manga_chapter(path, uuid.uuid1())
File "/Manga-Tagger/MangaTaggerLib/MangaTaggerLib.py", line 107, in process_manga_chapter
CURRENTLY_PENDING_RENAME.remove(new_file_path)
KeyError: PosixPath('/manga/xxxxxxxx/xxxxxxxx 001.cbz')
2021-02-28 16:49:34,900 | MTT-4 140034508569400 | MangaTaggerLib.task_queue.QueueWorker | WARNING - Manga Tagger is unfamiliar with this error. Please log an issue for investigation.
2021-02-28 16:49:35,778 | MTT-5 140034507447096 | MangaTaggerLib.MangaTaggerLib | INFO - Comparing titles found for "xxxxxxxx"...
2021-02-28 16:49:35,791 | MTT-5 140034507447096 | MangaTaggerLib.MangaTaggerLib | INFO - Match found for xxxxxxxx
2021-02-28 16:49:35,791 | MTT-5 140034507447096 | MangaTaggerLib.MangaTaggerLib | INFO - ID for "xxxxxxxx" found as "21600".
2021-02-28 16:49:36,031 | MTT-5 140034507447096 | MangaTaggerLib.models.Metadata | INFO - Creating Metadata model for series "xxxxxxxx"...
2021-02-28 16:49:36,078 | MTT-5 140034507447096 | MangaTaggerLib.models.Metadata | INFO - Parsing genres...
2021-02-28 16:49:36,079 | MTT-5 140034507447096 | MangaTaggerLib.models.Metadata | INFO - Parsing staff roles...
2021-02-28 16:49:36,084 | MTT-5 140034507447096 | MangaTaggerLib.models.Metadata | INFO - Parsing serializations...
2021-02-28 16:49:36,172 | MTT-5 140034507447096 | MangaTaggerLib.models.Metadata | INFO - Successfully created Metadata model.
2021-02-28 16:49:36,173 | MTT-5 140034507447096 | MangaTaggerLib.database.MetadataTable | INFO - Attempting to insert record into the database...
2021-02-28 16:49:36,184 | MTT-5 140034507447096 | MangaTaggerLib.database.MetadataTable | ERROR - key 'Jump SQ.19' must not contain '.'
Traceback (most recent call last):
File "/Manga-Tagger/MangaTaggerLib/database.py", line 94, in insert
cls._database.insert_one(data.dict)
File "/usr/lib/python3.8/site-packages/pymongo/collection.py", line 698, in insert_one
self._insert(document,
File "/usr/lib/python3.8/site-packages/pymongo/collection.py", line 613, in _insert
return self._insert_one(
File "/usr/lib/python3.8/site-packages/pymongo/collection.py", line 602, in _insert_one
self.__database.client._retryable_write(
File "/usr/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1498, in _retryable_write
return self._retry_with_session(retryable, func, s, None)
File "/usr/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1384, in _retry_with_session
return self._retry_internal(retryable, func, session, bulk)
File "/usr/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1416, in _retry_internal
return func(session, sock_info, retryable)
File "/usr/lib/python3.8/site-packages/pymongo/collection.py", line 590, in _insert_command
result = sock_info.command(
File "/usr/lib/python3.8/site-packages/pymongo/pool.py", line 699, in command
self._raise_connection_failure(error)
File "/usr/lib/python3.8/site-packages/pymongo/pool.py", line 683, in command
return command(self, dbname, spec, slave_ok,
File "/usr/lib/python3.8/site-packages/pymongo/network.py", line 120, in command
request_id, msg, size, max_doc_size = message._op_msg(
File "/usr/lib/python3.8/site-packages/pymongo/message.py", line 714, in _op_msg
return _op_msg_uncompressed(
bson.errors.InvalidDocument: key 'Jump SQ.19' must not contain '.'
2021-02-28 16:49:36,190 | MTT-5 140034507447096 | MangaTaggerLib.MangaTaggerLib | INFO - Retrieved metadata for "xxxxxxxx" from the Anilist and MyAnimeList APIs; now unlocking series for processing!
2021-02-28 16:49:36,192 | MTT-5 140034507447096 | MangaTaggerLib.MangaTaggerLib | INFO - Serie cover image already exist, not downloading.
2021-02-28 16:49:36,194 | MTT-5 140034507447096 | MangaTaggerLib.MangaTaggerLib | INFO - Constructing comicinfo object for "YYYYYYY", chapter 001...
2021-02-28 16:49:36,196 | MTT-5 140034507447096 | MangaTaggerLib.MangaTaggerLib | INFO - Finished creating ComicInfo object for "YYYYYYY", chapter 001.
2021-02-28 16:49:36,438 | MTT-5 140034507447096 | MangaTaggerLib.MangaTaggerLib | INFO - ComicInfo.xml has been created and appended to "/manga/xxxxxxxx/xxxxxxxx 001.cbz".
2021-02-28 16:49:36,440 | MTT-5 140034507447096 | MangaTaggerLib.MangaTaggerLib | INFO - Processing on "/manga/xxxxxxxx/xxxxxxxx 001.cbz" has finished.
**Log File**: Please make sure JSON logging is enabled and upload the JSON log file.

**Comment by Banh-Canh** [comment]
Removed an useless '-' in my regex. I think it should work with the next docker image.

**Comment by Ablex222** [comment]
Believe it is resolved.
