### ISSUE TITLE
[Help required] Getting python error using docker image built from main branch.

### ISSUE THREAD

**Issue by ThePromidius** [Banh-Canh/Manga-Tagger#21]
## **OS**: What operating system are you running Manga Tagger on?
docker
## **Manga Tagger Version:** What version of Manga Tagger are you running?
1.2.3-alpha
## **Description of the issue:** Give a a clear and concise description of what the issue is.
I'm trying to create my own docker image from my fork.
At first i tried using the modified image. But i got this error.
So I tried building exactly your main branch and i still get this error.
The only change i made is the CI to build the docker image. 
This is the fork https://github.com/ThePromidius/Manga-Tagger

Your image in dockerhub works just fine.
I'm quite lost rn and i don't know how to proceed.

From what i could find on internet that error occurs when mongodb is outdated with a version prior to 3.0 but i have not modified the version in requirements.txt so it should be using the one described there.

There must be something I'm missing. Any help is welcomed.

## **Manga Series:** What manga series (singular or plural) were being tagged when the issue was encountered?
Konjiki no Word Master - Yuusha Yonin ni Makikomareta Unique Cheat
## **Log File**: Please make sure JSON logging is enabled and upload the JSON log file.
```2022-05-15 18:51:29,586 | Thread-1 140224423041848 | MangaTaggerLib.task_queue.SeriesHandler | INFO - Creation event for "/downloads/Konjiki no Word Master - Yuusha Yonin ni Makikomareta Unique Cheat/Konjiki no Word Master - Yuusha Yonin ni Makikomareta Unique Cheat -.- Vol. 02 Ch. 006 - A Sudden Encounter, Part 2.cbz" will be added to the queue
2022-05-15 18:51:29,600 | MTT-0 140224434350904 | MangaTaggerLib.task_queue.QueueWorker | INFO - Pulling "file created" event from the queue for "/downloads/Konjiki no Word Master - Yuusha Yonin ni Makikomareta Unique Cheat/Konjiki no Word Master - Yuusha Yonin ni Makikomareta Unique Cheat -.- Vol. 02 Ch. 006 - A Sudden Encounter, Part 2.cbz"
2022-05-15 18:51:30,601 | MTT-0 140224434350904 | MangaTaggerLib.MangaTaggerLib | INFO - Now processing "/downloads/Konjiki no Word Master - Yuusha Yonin ni Makikomareta Unique Cheat/Konjiki no Word Master - Yuusha Yonin ni Makikomareta Unique Cheat -.- Vol. 02 Ch. 006 - A Sudden Encounter, Part 2.cbz"...
2022-05-15 18:51:30,602 | MTT-0 140224434350904 | MangaTaggerLib.MangaTaggerLib | INFO - Attempting to rename "Konjiki no Word Master - Yuusha Yonin ni Makikomareta Unique Cheat -.- Vol. 02 Ch. 006 - A Sudden Encounter, Part 2.cbz"...
2022-05-15 18:51:30,602 | MTT-0 140224434350904 | MangaTaggerLib.MangaTaggerLib | INFO - Filename was successfully parsed as ['Konjiki no Word Master - Yuusha Yonin ni Makikomareta Unique Cheat', 'Vol. 02 Ch. 006 - A Sudden Encounter, Part 2.cbz'].
2022-05-15 18:51:30,602 | MTT-0 140224434350904 | MangaTaggerLib.MangaTaggerLib | INFO - Table search value is "Konjiki no Word Master - Yuusha Yonin ni Makikomareta Unique Cheat"
2022-05-15 18:51:30,602 | MTT-0 140224434350904 | MangaTaggerLib.MangaTaggerLib | INFO - Searching manga_metadata for manga title by search value...
2022-05-15 18:51:30,603 | MTT-0 140224434350904 | MangaTaggerLib.MangaTaggerLib | INFO - Searching manga_metadata for regular manga title...
2022-05-15 18:51:30,604 | MTT-0 140224434350904 | MangaTaggerLib.MangaTaggerLib | INFO - Searching manga_metadata for English manga title...
2022-05-15 18:51:30,605 | MTT-0 140224434350904 | MangaTaggerLib.MangaTaggerLib | INFO - Manga was not found in the database; resorting to Anilist API.
2022-05-15 18:51:30,911 | MTT-0 140224434350904 | MangaTaggerLib.MangaTaggerLib | INFO - Manga title found for "Konjiki no Word Master - Yuusha Yonin ni Makikomareta Unique Cheat" found as "Konjiki no Word Master: Yuusha Yonin ni Makikomareta Unique Cheat".
2022-05-15 18:51:31,130 | MTT-0 140224434350904 | MangaTaggerLib.MangaTaggerLib | INFO - Checking for current and previously processed files with filename "Konjiki no Word Master Yuusha Yonin ni Makikomareta Unique Cheat 006.cbz"...
2022-05-15 18:51:31,131 | MTT-0 140224434350904 | MangaTaggerLib.MangaTaggerLib | INFO - No files currently currently being processed under the filename "Konjiki no Word Master Yuusha Yonin ni Makikomareta Unique Cheat 006.cbz". Locking new filename for processing...
2022-05-15 18:51:31,133 | MTT-0 140224434350904 | MangaTaggerLib.MangaTaggerLib | INFO - "Konjiki no Word Master: Yuusha Yonin ni Makikomareta Unique Cheat" chapter 006 has not been processed before. Proceeding with file rename...
2022-05-15 18:51:31,188 | MTT-0 140224434350904 | MangaTaggerLib.MangaTaggerLib | INFO - "Konjiki no Word Master Yuusha Yonin ni Makikomareta Unique Cheat 006" has been renamed.
2022-05-15 18:51:31,188 | MTT-0 140224434350904 | MangaTaggerLib.task_queue.QueueWorker | ERROR - 'Collection' object is not callable. If you meant to call the 'insert' method on a 'Collection' object it is failing because no such method exists.
Traceback (most recent call last):
  File "/app/Manga-Tagger/MangaTaggerLib/task_queue.py", line 188, in process
    MangaTaggerLib.process_manga_chapter(path, uuid.uuid1())
  File "/app/Manga-Tagger/MangaTaggerLib/MangaTaggerLib.py", line 68, in process_manga_chapter
    metadata_tagger(file_path, manga_details[0], manga_details[1], manga_details[2], logging_info)
  File "/app/Manga-Tagger/MangaTaggerLib/MangaTaggerLib.py", line 422, in metadata_tagger
    rename_action(file_path, new_file_path, series_title, manga_chapter_number, logging_info)
  File "/app/Manga-Tagger/MangaTaggerLib/MangaTaggerLib.py", line 177, in rename_action
    ProcFilesTable.insert_record(current_file_path, new_file_path, manga_title, chapter_number,
  File "/app/Manga-Tagger/MangaTaggerLib/database.py", line 217, in insert_record
    cls._database.insert(record, logging_info)
  File "/usr/lib/python3.8/site-packages/pymongo/collection.py", line 3166, in __call__
    raise TypeError(
TypeError: 'Collection' object is not callable. If you meant to call the 'insert' method on a 'Collection' object it is failing because no such method exists.
2022-05-15 18:51:31,188 | MTT-0 140224434350904 | MangaTaggerLib.task_queue.QueueWorker | WARNING - Manga Tagger is unfamiliar with this error. Please log an issue for investigation.```

**Comment by Banh-Canh** [comment]
Hello, in the main branch, the dockerfile/build ignore the requirement.txt... rookie mistakes of mine because I had some trouble pinning version with alpine. Can you try building my dev branch and see if it works ?

The main branch's version modules aren't pinned so it could cause trouble I guess.

**Comment by ThePromidius** [comment]
Hey! Thanks for the quick response.
Image just finished building and deploy. 
Seems that your dev branch works just fine indeed. 
Ohhh Ok. I just saw what you meant about dockerfile not including requirements.txt
Going to try adding it to my version see if it works.

**Comment by ThePromidius** [comment]
That fixed it. It now works with my changes as well
Honestly didn't expect such a quick answer. 
Thank you!
