### ISSUE TITLE
Exeption.json not working (as expected) ?

### ISSUE THREAD

**Issue by HerrFrutti** [Banh-Canh/Manga-Tagger#22]
**OS**: Fedora Server

**Manga Tagger Version:** [release-v1.2.2-alpha]

**Description of the issue:** exeptions.json not working like I'd expect it to...

Boruto: Naruto Next Generations (if fmd2 downloads from mangaplus the series name is Boruto: Naruto Next Generations [en] and that causes an error. So I wanted to create an exeption.  
From my compose file:
```
 volumes:
      - ./config:/config:z
```
exeptions.json stored like: `config/data/exceptions.json`

**Manga Series:** Boruto: Naruto Next Generations (if fmd2 downloads from mangaplus the series name is Boruto: Naruto Next Generations [en] and that causes an error. 

```
{
        "Boruto: Naruto Next Generations [en]": {
                "anilist_title": "Boruto: Naruto Next Generations",
        "format": "Manga",
        "adult": false
        }
}
```

**Log File**: 
```
2022-05-25 21:31:36,907 | Thread-1 140098638363448 | MangaTaggerLib.task_queue.SeriesHandler | INFO - Creation event for "/downloads/Boruto Naruto Next Generations/Boruto Naruto Next Generations [en] -.- Number 069 Captives.cbz" will be added to the queue
2022-05-25 21:31:37,240 | MTT-1 140098648632120 | MangaTaggerLib.task_queue.QueueWorker | INFO - Pulling "file created" event from the queue for "/downloads/Boruto Naruto Next Generations/Boruto Naruto Next Generations [en] -.- Number 069 Captives.cbz"
2022-05-25 21:31:38,247 | MTT-1 140098648632120 | MangaTaggerLib.MangaTaggerLib | INFO - Now processing "/downloads/Boruto Naruto Next Generations/Boruto Naruto Next Generations [en] -.- Number 069 Captives.cbz"...
2022-05-25 21:31:38,249 | MTT-1 140098648632120 | MangaTaggerLib.MangaTaggerLib | INFO - Attempting to rename "Boruto Naruto Next Generations [en] -.- Number 069 Captives.cbz"...
2022-05-25 21:31:38,249 | MTT-1 140098648632120 | MangaTaggerLib.MangaTaggerLib | INFO - Filename was successfully parsed as ['Boruto Naruto Next Generations [en]', 'Number 069 Captives.cbz'].
2022-05-25 21:31:38,254 | MTT-1 140098648632120 | MangaTaggerLib.MangaTaggerLib | INFO - Table search value is "Boruto Naruto Next Generations [en]"
2022-05-25 21:31:38,254 | MTT-1 140098648632120 | MangaTaggerLib.MangaTaggerLib | INFO - Searching manga_metadata for manga title by search value...
2022-05-25 21:31:38,288 | MTT-1 140098648632120 | MangaTaggerLib.MangaTaggerLib | INFO - Searching manga_metadata for regular manga title...
2022-05-25 21:31:38,290 | MTT-1 140098648632120 | MangaTaggerLib.MangaTaggerLib | INFO - Searching manga_metadata for English manga title...
2022-05-25 21:31:38,293 | MTT-1 140098648632120 | MangaTaggerLib.MangaTaggerLib | INFO - Manga was not found in the database; resorting to Anilist API.
2022-05-25 21:31:38,703 | MTT-1 140098648632120 | MangaTaggerLib.task_queue.QueueWorker | ERROR - "Boruto Naruto Next Generations [en]" was not found in the returned results from Anilist This may be due to a difference in manga series titles, or may be something else entirely. Please open an issue for investigation.
Traceback (most recent call last):
  File "/app/Manga-Tagger/MangaTaggerLib/task_queue.py", line 188, in process
    MangaTaggerLib.process_manga_chapter(path, uuid.uuid1())
  File "/app/Manga-Tagger/MangaTaggerLib/MangaTaggerLib.py", line 68, in process_manga_chapter
    metadata_tagger(file_path, manga_details[0], manga_details[1], manga_details[2], logging_info)
  File "/app/Manga-Tagger/MangaTaggerLib/MangaTaggerLib.py", line 313, in metadata_tagger
    raise MangaNotFoundError(manga_title)
MangaTaggerLib.errors.MangaNotFoundError: "Boruto Naruto Next Generations [en]" was not found in the returned results from Anilist This may be due to a difference in manga series titles, or may be something else entirely. Please open an issue for investigation.
2022-05-25 21:31:38,706 | MTT-1 140098648632120 | MangaTaggerLib.task_queue.QueueWorker | WARNING - Manga Tagger is unfamiliar with this error. Please log an issue for investigation.
```

Any hint what I did wrong?

**Comment by ThePromidius** [comment]
Pretty sure the issue is that you have the extra `:`
instead of `Boruto: Naruto Next Generations [en]` it should be `Boruto Naruto Next Generations [en]` since that's how the files are named

**Comment by HerrFrutti** [comment]
Damn I missed that.. I'll give it a try and give you feedback.

**Comment by HerrFrutti** [comment]
that worked. thanks
