### ISSUE TITLE
[BUG] SERIES CONTAINING ':' NOT BEING EDITED AND MOVED BY MANGATAGGER

### ISSUE THREAD

**Issue by NotxNero** [Banh-Canh/Manga-Tagger#36]
**OS**: Windows 11

**Manga Tagger Version:** ![image](https://user-images.githubusercontent.com/122322489/214738295-44a446e9-5bb9-45eb-871e-5b7af0125b77.png)

**Description of the issue:** When using manga tagger specifically on "tokyo ghoul:re", after adding it to exceptions.json it checks every chapter and isn't able to add metadata and move them. the cause of this is unknown to me.

**Manga Series:** [Tokyo ghoul:re
](https://anilist.co/manga/85611/Tokyo-Ghoulre/)

[MangaTagger.log](https://github.com/MangaManagerORG/Manga-Tagger/files/10505660/MangaTagger.log)

emptied logs before recreating this problem^^

**Comment by ThePromidius** [comment]
For the log this seems to be the issue
```log
2023-01-26 01:51:22,043 | MTT-5 1532 | MangaTaggerLib.MangaTaggerLib | INFO - Table search value is "Tokyo Ghoulre"
023-01-26 01:51:22,044 | MTT-5 1532 | MangaTaggerLib.MangaTaggerLib | INFO - Searching manga_metadata for anilist id.
2023-01-26 01:51:22,051 | MTT-5 1532 | MangaTaggerLib.task_queue.QueueWorker | ERROR - 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Manga-Tagger\MangaTaggerLib\task_queue.py", line 188, in process
    MangaTaggerLib.process_manga_chapter(path, uuid.uuid1())
  File "C:\Manga-Tagger\MangaTaggerLib\MangaTaggerLib.py", line 68, in process_manga_chapter
    metadata_tagger(file_path, manga_details[0], manga_details[1], manga_details[2], logging_info, manga_details[3])
  File "C:\Manga-Tagger\MangaTaggerLib\MangaTaggerLib.py", line 338, in metadata_tagger
    series_title = MetadataTable.search_series_title(manga_title)
  File "C:\Manga-Tagger\MangaTaggerLib\database.py", line 166, in search_series_title
    return cls._database.find_one({"$or": [
TypeError: 'NoneType' object is not subscriptable```
