### ISSUE TITLE
[BUG] Chaper not parsed correctly

### ISSUE THREAD

**Issue by HerrFrutti** [Banh-Canh/Manga-Tagger#37]
**OS**: Fedora Linux (Podman Container)

**Manga Tagger Version:** Docker Version 

**Description of the issue:**

`Boruto Two Blue Vortex -.- 001 Boruto.cbz` this file name did not work. Changing to `Boruto Two Blue Vortex -.- Ch 001 Boruto.cbz' worked... this would be a manual fix for every chapter and I think other manga I downloaded did not need this renaming from my part.

**Manga Series:** BORUTO: TWO BLUE VORTEX

**Log File**:

```
2023-08-24 19:17:17,283 | MainThread 140561289304904 | MangaTaggerLib.task_queue.QueueWorker | INFO - Watching "/downloads" for new downloads

2023-08-24 19:17:18,292 | MTT-0 140561231457080 | MangaTaggerLib.MangaTaggerLib | INFO - Now processing "/downloads/Boruto Two Blue Vortex/Boruto Two Blue Vortex -.- 001 Boruto.cbz"...

2023-08-24 19:17:18,293 | MTT-0 140561231457080 | MangaTaggerLib.MangaTaggerLib | INFO - Attempting to rename "Boruto Two Blue Vortex -.- 001 Boruto.cbz"...

2023-08-24 19:17:18,293 | MTT-0 140561231457080 | MangaTaggerLib.MangaTaggerLib | INFO - Filename was successfully parsed as ['Boruto Two Blue Vortex', '001 Boruto.cbz'].

2023-08-24 19:17:18,295 | MTT-0 140561231457080 | MangaTaggerLib.MangaTaggerLib | ERROR - Unable to parse filename "['Boruto Two Blue Vortex', '001 Boruto.cbz']" due to delimiter "ch/chapter" missing

Traceback (most recent call last):

  File "/app/Manga-Tagger/MangaTaggerLib/MangaTaggerLib.py", line 141, in filename_parser

    raise UnparsableFilenameError(filename, 'ch/chapter')

MangaTaggerLib.errors.UnparsableFilenameError: Unable to parse filename "['Boruto Two Blue Vortex', '001 Boruto.cbz']" due to delimiter "ch/chapter" missing

2023-08-24 19:17:18,296 | MTT-0 140561231457080 | MangaTaggerLib.task_queue.QueueWorker | ERROR - 'NoneType' object is not subscriptable

Traceback (most recent call last):

  File "/app/Manga-Tagger/MangaTaggerLib/task_queue.py", line 188, in process

    MangaTaggerLib.process_manga_chapter(path, uuid.uuid1())

  File "/app/Manga-Tagger/MangaTaggerLib/MangaTaggerLib.py", line 68, in process_manga_chapter

    metadata_tagger(file_path, manga_details[0], manga_details[1], manga_details[2], logging_info, manga_details[3])

TypeError: 'NoneType' object is not subscriptable
```

**Comment by HerrFrutti** [comment]
still the same :)

**Comment by StayBlue** [comment]
I'm getting the same error

**Comment by Jerrk** [comment]
Are you using %NUMBERING% instead of %CHAPTER%?

iirc %CHAPTER% includes the ch. prefix in addition to the numbering

**Comment by StayBlue** [comment]
> Are you using %NUMBERING% instead of %CHAPTER%?
> 
> iirc %CHAPTER% includes the ch. prefix in addition to the numbering

Thanks for the reply! I ended up prefixing the chapter number with `Ch`, as the original issue suggested, so it ended up becoming like:
`MANGA TITLE -.- Ch CHAPTER NUMBER`
That seemed to do the trick for me. Hope this helps someone else who stumbles upon this!

**Comment by HerrFrutti** [comment]
> > Are you using %NUMBERING% instead of %CHAPTER%?
> > iirc %CHAPTER% includes the ch. prefix in addition to the numbering
> 
> Thanks for the reply! I ended up prefixing the chapter number with `Ch`, as the original issue suggested, so it ended up becoming like: `MANGA TITLE -.- Ch CHAPTER NUMBER` That seemed to do the trick for me. Hope this helps someone else who stumbles upon this!

yeah this does the trick for me too

**Comment by ThePromidius** [comment]
Closing this then.
FYI that's explained in the wiki https://github.com/MangaManagerORG/Manga-Tagger/wiki
