### ISSUE TITLE
[BUG] ERROR - 'synonyms'

### ISSUE THREAD

**Issue by StayBlue** [Banh-Canh/Manga-Tagger#38]
**OS**: Docker

**Manga Tagger Version:** Nightly build

**Description of the issue:** Getting an error while using the Docker Container. This is after it downloaded the metadata (finally) and moved all the files into the appropriate folder

**Manga Series:** Kaoru Hana wa Rin to Saku

**Screenshots (If applicable):** N/A

**Log File**: Logs are below
<details><summary>Logs</summary>
<p>

```
 2024-01-07 01:56:55,169 | MTT-0 140507407444792 | MangaTaggerLib.MangaTaggerLib | INFO - "Kaoru Hana wa Rin to Saku" chapter 0092 has not been processed before. Proceeding with file rename...
 

 2024-01-07 01:56:55,171 | MTT-2 140507405323064 | MangaTaggerLib.MangaTaggerLib | INFO - No files currently currently being processed under the filename "Kaoru Hana wa Rin to Saku 0059.cbz". Locking new filename for processing...
 

 2024-01-07 01:56:55,173 | MTT-4 140507403201336 | MangaTaggerLib.MangaTaggerLib | INFO - No files currently currently being processed under the filename "Kaoru Hana wa Rin to Saku 0013.cbz". Locking new filename for processing...
 

 2024-01-07 01:56:55,175 | MTT-2 140507405323064 | MangaTaggerLib.MangaTaggerLib | INFO - "Kaoru Hana wa Rin to Saku" chapter 0059 has not been processed before. Proceeding with file rename...
 

 2024-01-07 01:56:55,175 | MTT-4 140507403201336 | MangaTaggerLib.MangaTaggerLib | INFO - "Kaoru Hana wa Rin to Saku" chapter 0013 has not been processed before. Proceeding with file rename...
 

 2024-01-07 01:56:55,184 | MTT-0 140507407444792 | MangaTaggerLib.MangaTaggerLib | INFO - "Kaoru Hana wa Rin to Saku 0092" has been renamed.
 

 2024-01-07 01:56:55,185 | MTT-0 140507407444792 | MangaTaggerLib.MangaTaggerLib | INFO - "Kaoru Hana wa Rin to Saku 0092.cbz" will be unlocked for any pending processes.
 

 2024-01-07 01:56:55,185 | MTT-0 140507407444792 | MangaTaggerLib.MangaTaggerLib | INFO - Found an entry in manga_metadata for "The Fragrant Flower Blooms With Dignity".
 

 2024-01-07 01:56:55,186 | MTT-0 140507407444792 | MangaTaggerLib.MangaTaggerLib | INFO - Image flag not set, not downloading series cover image.
 

 2024-01-07 01:56:55,186 | MTT-0 140507407444792 | MangaTaggerLib.models.Metadata | INFO - Creating Metadata model for series "Kaoru Hana wa Rin to Saku"...
 

 2024-01-07 01:56:55,186 | MTT-0 140507407444792 | MangaTaggerLib.task_queue.QueueWorker | ERROR - 'synonyms'
 

 Traceback (most recent call last):
 

   File "/app/Manga-Tagger/MangaTaggerLib/task_queue.py", line 189, in process
 

     MangaTaggerLib.process_manga_chapter(path, uuid.uuid1())
 

   File "/app/Manga-Tagger/MangaTaggerLib/MangaTaggerLib.py", line 68, in process_manga_chapter
 

     metadata_tagger(file_path, manga_details[0], manga_details[1], manga_details[2], logging_info, manga_details[3])
 

   File "/app/Manga-Tagger/MangaTaggerLib/MangaTaggerLib.py", line 401, in metadata_tagger
 

     manga_metadata = Metadata(series_title, logging_info, details=manga_search)
 

   File "/app/Manga-Tagger/MangaTaggerLib/models.py", line 25, in __init__
 

     self._construct_database_metadata(details)
 

   File "/app/Manga-Tagger/MangaTaggerLib/models.py", line 80, in _construct_database_metadata
 

     self.synonyms = details['synonyms']
 

 KeyError: 'synonyms'
 

 2024-01-07 01:56:55,186 | MTT-0 140507407444792 | MangaTaggerLib.task_queue.QueueWorker | WARNING - Manga Tagger is unfamiliar with this error. Please log an issue for investigation.
 

 2024-01-07 01:56:55,189 | MTT-2 140507405323064 | MangaTaggerLib.MangaTaggerLib | INFO - "Kaoru Hana wa Rin to Saku 0059" has been renamed.
 

 2024-01-07 01:56:55,190 | MTT-2 140507405323064 | MangaTaggerLib.MangaTaggerLib | INFO - "Kaoru Hana wa Rin to Saku 0059.cbz" will be unlocked for any pending processes.
 

 2024-01-07 01:56:55,190 | MTT-2 140507405323064 | MangaTaggerLib.MangaTaggerLib | INFO - Found an entry in manga_metadata for "The Fragrant Flower Blooms With Dignity".
 

 2024-01-07 01:56:55,190 | MTT-2 140507405323064 | MangaTaggerLib.MangaTaggerLib | INFO - Image flag not set, not downloading series cover image.
 

 2024-01-07 01:56:55,190 | MTT-2 140507405323064 | MangaTaggerLib.models.Metadata | INFO - Creating Metadata model for series "Kaoru Hana wa Rin to Saku"...
 

 2024-01-07 01:56:55,190 | MTT-2 140507405323064 | MangaTaggerLib.task_queue.QueueWorker | ERROR - 'synonyms'
 

 Traceback (most recent call last):
 

   File "/app/Manga-Tagger/MangaTaggerLib/task_queue.py", line 189, in process
 

     MangaTaggerLib.process_manga_chapter(path, uuid.uuid1())
 

   File "/app/Manga-Tagger/MangaTaggerLib/MangaTaggerLib.py", line 68, in process_manga_chapter
 

     metadata_tagger(file_path, manga_details[0], manga_details[1], manga_details[2], logging_info, manga_details[3])
 

   File "/app/Manga-Tagger/MangaTaggerLib/MangaTaggerLib.py", line 401, in metadata_tagger
```

</p>
</details>

<details><summary>exceptions.json</summary>
<p>

```json
{
        "Kaoru Hana Wa Rin To Saku": {
                "anilist_title": "The Fragrant Flower Blooms With Dignity",
                "format": "MANGA",
                "adult": false
        }
}
```

Note: I did originally try to use the anilist_id instead of the anilist_title, but that caused it to break completely.
</p>
</details>

**Comment by Jerrk** [comment]
I appear to have this issue as well.

The chapter gets renamed and moved but the cover and the comicinfo is not added to the resulting .cbz file. The manga folder in /downloads isn't deleted either.

```
2024-02-06 04:50:04,540 | MTT-0 23143758355256 | MangaTaggerLib.MangaTaggerLib | INFO - Now processing "/downloads/Ijiranaide, Nagatoro-san/Ijiranaide, Nagatoro-san -.- Ch. 144 - Senpai... even for you, that was... [Ecchi No Doujinshi Scans, anonymous] [MangaDex].cbz"...
2024-02-06 04:50:04,540 | MTT-0 23143758355256 | MangaTaggerLib.MangaTaggerLib | INFO - Attempting to rename "Ijiranaide, Nagatoro-san -.- Ch. 144 - Senpai... even for you, that was... [Ecchi No Doujinshi Scans, anonymous] [MangaDex].cbz"...
2024-02-06 04:50:04,541 | MTT-0 23143758355256 | MangaTaggerLib.MangaTaggerLib | INFO - Filename was successfully parsed as ['Ijiranaide, Nagatoro-san', 'Ch. 144 - Senpai... even for you, that was... [Ecchi No Doujinshi Scans, anonymous] [MangaDex].cbz'].
2024-02-06 04:50:04,542 | MTT-0 23143758355256 | MangaTaggerLib.MangaTaggerLib | INFO - Table search value is "Ijiranaide, Nagatoro-san"
2024-02-06 04:50:04,543 | MTT-0 23143758355256 | MangaTaggerLib.MangaTaggerLib | INFO - Searching manga_metadata for manga title by search value...
2024-02-06 04:50:04,548 | MTT-0 23143758355256 | MangaTaggerLib.MangaTaggerLib | INFO - No files currently currently being processed under the filename "Ijiranaide Nagatoro-san 144.cbz". Locking new filename for processing...
2024-02-06 04:50:04,560 | MTT-0 23143758355256 | MangaTaggerLib.MangaTaggerLib | INFO - "Ijiranaide, Nagatoro-san" chapter 144 has not been processed before. Proceeding with file rename...
2024-02-06 04:50:04,645 | MTT-0 23143758355256 | MangaTaggerLib.MangaTaggerLib | INFO - "Ijiranaide Nagatoro-san 144" has been renamed.
2024-02-06 04:50:04,647 | MTT-0 23143758355256 | MangaTaggerLib.MangaTaggerLib | INFO - "Ijiranaide Nagatoro-san 144.cbz" will be unlocked for any pending processes.
2024-02-06 04:50:04,647 | MTT-0 23143758355256 | MangaTaggerLib.MangaTaggerLib | INFO - Found an entry in manga_metadata for "Ijiranaide, Nagatoro-san"; unlocking series for processing.
2024-02-06 04:50:04,648 | MTT-0 23143758355256 | MangaTaggerLib.MangaTaggerLib | INFO - Series cover image already exist, not downloading.
2024-02-06 04:50:04,648 | MTT-0 23143758355256 | MangaTaggerLib.models.Metadata | INFO - Creating Metadata model for series "Ijiranaide, Nagatoro-san"...
2024-02-06 04:50:04,648 | MTT-0 23143758355256 | MangaTaggerLib.task_queue.QueueWorker | ERROR - 'synonyms'
Traceback (most recent call last):
  File "/app/Manga-Tagger/MangaTaggerLib/task_queue.py", line 189, in process
    MangaTaggerLib.process_manga_chapter(path, uuid.uuid1())
  File "/app/Manga-Tagger/MangaTaggerLib/MangaTaggerLib.py", line 68, in process_manga_chapter
    metadata_tagger(file_path, manga_details[0], manga_details[1], manga_details[2], logging_info, manga_details[3])
  File "/app/Manga-Tagger/MangaTaggerLib/MangaTaggerLib.py", line 401, in metadata_tagger
    manga_metadata = Metadata(series_title, logging_info, details=manga_search)
  File "/app/Manga-Tagger/MangaTaggerLib/models.py", line 25, in __init__
    self._construct_database_metadata(details)
  File "/app/Manga-Tagger/MangaTaggerLib/models.py", line 80, in _construct_database_metadata
    self.synonyms = details['synonyms']
KeyError: 'synonyms'
2024-02-06 04:50:04,649 | MTT-0 23143758355256 | MangaTaggerLib.task_queue.QueueWorker | WARNING - Manga Tagger is unfamiliar with this error. Please log an issue for investigation.
```
